import comp from "/Users/guoguo/code/my-project/shixinde-apifox-swagger/docs-vuepress/.vuepress/.temp/pages/cli.html.vue"
const data = JSON.parse("{\"path\":\"/cli.html\",\"title\":\"命令行工具\",\"lang\":\"zh-CN\",\"frontmatter\":{},\"headers\":[{\"level\":2,\"title\":\"基本语法\",\"slug\":\"基本语法\",\"link\":\"#基本语法\",\"children\":[]},{\"level\":2,\"title\":\"命令行选项\",\"slug\":\"命令行选项\",\"link\":\"#命令行选项\",\"children\":[{\"level\":3,\"title\":\"必需选项\",\"slug\":\"必需选项\",\"link\":\"#必需选项\",\"children\":[]},{\"level\":3,\"title\":\"认证选项\",\"slug\":\"认证选项\",\"link\":\"#认证选项\",\"children\":[]},{\"level\":3,\"title\":\"导出范围选项\",\"slug\":\"导出范围选项\",\"link\":\"#导出范围选项\",\"children\":[]},{\"level\":3,\"title\":\"其他选项\",\"slug\":\"其他选项\",\"link\":\"#其他选项\",\"children\":[]}]},{\"level\":2,\"title\":\"使用示例\",\"slug\":\"使用示例\",\"link\":\"#使用示例\",\"children\":[{\"level\":3,\"title\":\"1. 基本导出\",\"slug\":\"_1-基本导出\",\"link\":\"#_1-基本导出\",\"children\":[]},{\"level\":3,\"title\":\"2. 使用访问令牌\",\"slug\":\"_2-使用访问令牌\",\"link\":\"#_2-使用访问令牌\",\"children\":[]},{\"level\":3,\"title\":\"3. 导出指定文件夹\",\"slug\":\"_3-导出指定文件夹\",\"link\":\"#_3-导出指定文件夹\",\"children\":[]},{\"level\":3,\"title\":\"4. 环境变量配合使用\",\"slug\":\"_4-环境变量配合使用\",\"link\":\"#_4-环境变量配合使用\",\"children\":[]},{\"level\":3,\"title\":\"5. 在 package.json 中使用\",\"slug\":\"_5-在-package-json-中使用\",\"link\":\"#_5-在-package-json-中使用\",\"children\":[]}]},{\"level\":2,\"title\":\"高级用法\",\"slug\":\"高级用法\",\"link\":\"#高级用法\",\"children\":[{\"level\":3,\"title\":\"1. 批量导出多个模块\",\"slug\":\"_1-批量导出多个模块\",\"link\":\"#_1-批量导出多个模块\",\"children\":[]},{\"level\":3,\"title\":\"2. 与 CI/CD 集成\",\"slug\":\"_2-与-ci-cd-集成\",\"link\":\"#_2-与-ci-cd-集成\",\"children\":[]},{\"level\":3,\"title\":\"3. 监听文件变化自动导出\",\"slug\":\"_3-监听文件变化自动导出\",\"link\":\"#_3-监听文件变化自动导出\",\"children\":[]}]},{\"level\":2,\"title\":\"错误处理\",\"slug\":\"错误处理\",\"link\":\"#错误处理\",\"children\":[{\"level\":3,\"title\":\"常见错误码\",\"slug\":\"常见错误码\",\"link\":\"#常见错误码\",\"children\":[]},{\"level\":3,\"title\":\"调试模式\",\"slug\":\"调试模式\",\"link\":\"#调试模式\",\"children\":[]}]},{\"level\":2,\"title\":\"性能优化\",\"slug\":\"性能优化\",\"link\":\"#性能优化\",\"children\":[{\"level\":3,\"title\":\"1. 并行导出\",\"slug\":\"_1-并行导出\",\"link\":\"#_1-并行导出\",\"children\":[]},{\"level\":3,\"title\":\"2. 缓存策略\",\"slug\":\"_2-缓存策略\",\"link\":\"#_2-缓存策略\",\"children\":[]}]},{\"level\":2,\"title\":\"下一步\",\"slug\":\"下一步\",\"link\":\"#下一步\",\"children\":[]}],\"git\":{\"updatedTime\":null,\"contributors\":[]},\"filePathRelative\":\"cli.md\",\"excerpt\":\"\\n<p><code>apifox-swagger</code> 提供了强大的命令行工具，支持多种导出模式和配置选项。</p>\\n<h2>基本语法</h2>\\n<div class=\\\"language-bash\\\" data-highlighter=\\\"prismjs\\\" data-ext=\\\"sh\\\" data-title=\\\"sh\\\"><pre class=\\\"language-bash\\\"><code><span class=\\\"line\\\">apifox-swagger <span class=\\\"token punctuation\\\">[</span>选项<span class=\\\"token punctuation\\\">]</span></span>\\n<span class=\\\"line\\\"></span></code></pre></div>\"}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
